platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
inputs:
- name: website_code
- name: resource_types

outputs:
- name: website_code
run:
  path: website_code/build.sh
